RF24Ethernet - TCP/IP over RF24Network: RF24UDP Class Reference
RF24UDP Class Reference
#include <RF24Udp.h>
Public Member Functions
RF24UDP ()
uint8_t begin (uint16_t)
void stop ()
int beginPacket (IPAddress ip, uint16_t port)
int beginPacket (const char *host, uint16_t port)
int endPacket ()
size_t write (uint8_t)
size_t write (const uint8_t *buffer, size_t size)
int parsePacket ()
int available ()
int read ()
int read (unsigned char *buffer, size_t len)
int read (char *buffer, size_t len)
int peek ()
void flush ()
IPAddress remoteIP ()
uint16_t remotePort ()
Friends
class RF24EthernetClass
class RF24Client
void uipudp_appcall (void)
Detailed Description
Definition at line 43 of file RF24Udp.h.
Constructor & Destructor Documentation
RF24UDP::RF24UDP ()
Definition at line 33 of file RF24Udp.cpp.
Member Function Documentation
uint8_t RF24UDP::begin (uint16_t port)
Definition at line 41 of file RF24Udp.cpp.
Referenced by DNSClient::getHostByName().
void RF24UDP::stop ()
Definition at line 58 of file RF24Udp.cpp.
References uip_udp_userdata_t::packet_in, uip_udp_userdata_t::packet_next, and uip_udp_userdata_t::packet_out.
Referenced by DNSClient::getHostByName().
int RF24UDP::beginPacket (IPAddress ip, uint16_t port)
Definition at line 81 of file RF24Udp.cpp.
References uip_udp_userdata_t::out_pos, and uip_udp_userdata_t::packet_out.
Referenced by beginPacket(), and DNSClient::getHostByName().
int RF24UDP::beginPacket (const char * host, uint16_t port)
Definition at line 145 of file RF24Udp.cpp.
References DNSClient::begin(), beginPacket(), RF24EthernetClass::dnsServerIP(), and DNSClient::getHostByName().
int RF24UDP::endPacket ()
Definition at line 164 of file RF24Udp.cpp.
References IF_RF24ETHERNET_DEBUG_UDP, uip_udp_userdata_t::packet_out, and uip_udp_userdata_t::send.
Referenced by DNSClient::getHostByName().
size_t RF24UDP::write (uint8_t c)
Definition at line 183 of file RF24Udp.cpp.
Referenced by DNSClient::BuildRequest().
size_t RF24UDP::write (const uint8_t * buffer, size_t size)
Definition at line 190 of file RF24Udp.cpp.
References RF24Client::all_data, IF_RF24ETHERNET_DEBUG_UDP, uip_udp_userdata_t::out_pos, and uip_udp_userdata_t::packet_out.
int RF24UDP::parsePacket ()
Definition at line 209 of file RF24Udp.cpp.
References uip_udp_userdata_t::packet_in, and uip_udp_userdata_t::packet_in_size.
Referenced by DNSClient::ProcessResponse().
int RF24UDP::available ()
Definition at line 246 of file RF24Udp.cpp.
References uip_udp_userdata_t::packet_in_size.
Referenced by DNSClient::ProcessResponse().
int RF24UDP::read ()
Definition at line 255 of file RF24Udp.cpp.
Referenced by DNSClient::ProcessResponse(), and read().
int RF24UDP::read (unsigned char * buffer, size_t len)
Definition at line 268 of file RF24Udp.cpp.
References RF24Client::all_data, uip_udp_userdata_t::in_pos, uip_udp_userdata_t::packet_in, and uip_udp_userdata_t::packet_in_size.
int RF24UDP::read (char * buffer, size_t len) inline
Definition at line 98 of file RF24Udp.h.
References read().
int RF24UDP::peek ()
Definition at line 294 of file RF24Udp.cpp.
References uip_udp_userdata_t::packet_in.
void RF24UDP::flush ()
Definition at line 308 of file RF24Udp.cpp.
References uip_udp_userdata_t::packet_in, and uip_udp_userdata_t::packet_in_size.
Referenced by DNSClient::ProcessResponse().
IPAddress RF24UDP::remoteIP ()
Definition at line 318 of file RF24Udp.cpp.
Referenced by DNSClient::ProcessResponse().
uint16_t RF24UDP::remotePort ()
Definition at line 325 of file RF24Udp.cpp.
Referenced by DNSClient::ProcessResponse().
Friends And Related Function Documentation
friend class RF24EthernetClass friend
Definition at line 121 of file RF24Udp.h.
friend class RF24Client friend
Definition at line 122 of file RF24Udp.h.
Referenced by RF24Server::available().
void uipudp_appcall (void) friend
Definition at line 333 of file RF24Udp.cpp.