RF24Ethernet - TCP/IP over RF24Network: DNSClient Class Reference
DNSClient Class Reference
#include <Dns.h>
Public Member Functions
void begin (const IPAddress &aDNSServer)
int inet_aton (const char *aIPAddrString, IPAddress &aResult)
int getHostByName (const char *aHostname, IPAddress &aResult)
Protected Member Functions
uint16_t BuildRequest (const char *aName)
uint16_t ProcessResponse (uint16_t aTimeout, IPAddress &aAddress)
Protected Attributes
IPAddress iDNSServer
uint16_t iRequestId
RF24UDP iUdp
Detailed Description
Definition at line 13 of file Dns.h.
Member Function Documentation
void DNSClient::begin (const IPAddress & aDNSServer)
Definition at line 47 of file Dns.cpp.
References iDNSServer, and iRequestId.
Referenced by RF24UDP::beginPacket(), and RF24Client::connect().
int DNSClient::inet_aton (const char * aIPAddrString, IPAddress & aResult)
Convert a numeric IP address string into a four-byte IP address.
Parameters
aIPAddrString IP address to convert
aResult IPAddress structure to store the returned IP address
Returns
1 if aIPAddrString was successfully converted to an IP address, else error code
Definition at line 54 of file Dns.cpp.
Referenced by getHostByName().
int DNSClient::getHostByName (const char * aHostname, IPAddress & aResult)
Resolve the given hostname to an IP address.
Parameters
aHostname Name to be resolved
aResult IPAddress structure to store the returned IP address
Returns
1 if aIPAddrString was successfully converted to an IP address, else error code
Definition at line 114 of file Dns.cpp.
References RF24UDP::begin(), RF24UDP::beginPacket(), BuildRequest(), RF24UDP::endPacket(), iDNSServer, IF_RF24ETHERNET_DEBUG_DNS, inet_aton(), iUdp, ProcessResponse(), and RF24UDP::stop().
Referenced by RF24UDP::beginPacket(), and RF24Client::connect().
uint16_t DNSClient::BuildRequest (const char * aName) protected
Definition at line 172 of file Dns.cpp.
References iRequestId, iUdp, and RF24UDP::write().
Referenced by getHostByName().
uint16_t DNSClient::ProcessResponse (uint16_t aTimeout, IPAddress & aAddress) protected
Definition at line 252 of file Dns.cpp.
References RF24UDP::available(), RF24UDP::flush(), iDNSServer, IF_RF24ETHERNET_DEBUG_DNS, iRequestId, iUdp, RF24UDP::parsePacket(), RF24UDP::read(), RF24UDP::remoteIP(), and RF24UDP::remotePort().
Referenced by getHostByName().
Member Data Documentation
IPAddress DNSClient::iDNSServer protected
Definition at line 39 of file Dns.h.
Referenced by begin(), getHostByName(), and ProcessResponse().
uint16_t DNSClient::iRequestId protected
Definition at line 40 of file Dns.h.
Referenced by begin(), BuildRequest(), and ProcessResponse().
RF24UDP DNSClient::iUdp protected
Definition at line 41 of file Dns.h.
Referenced by BuildRequest(), getHostByName(), and ProcessResponse().